// <auto-generated />
using System;
using Anetia_TripApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Anetia_TripApp.Migrations
{
    [DbContext(typeof(TripDbContext))]
    [Migration("20241118190949_trip2seed")]
    partial class trip2seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActivityTrip", b =>
                {
                    b.Property<int>("ActivitiesActivityId")
                        .HasColumnType("int");

                    b.Property<int>("TripsTripId")
                        .HasColumnType("int");

                    b.HasKey("ActivitiesActivityId", "TripsTripId");

                    b.HasIndex("TripsTripId");

                    b.ToTable("ActivityTrip");
                });

            modelBuilder.Entity("Anetia_TripApp.Models.Accommodation", b =>
                {
                    b.Property<int>("AccommodationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccommodationId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccommodationId");

                    b.ToTable("Accommodations");

                    b.HasData(
                        new
                        {
                            AccommodationId = 1,
                            Name = "Luxury Hotel Paris"
                        },
                        new
                        {
                            AccommodationId = 2,
                            Name = "Paris Central Inn"
                        },
                        new
                        {
                            AccommodationId = 3,
                            Name = "Manhattan Suites"
                        },
                        new
                        {
                            AccommodationId = 4,
                            Name = "Broadway Grand Hotel"
                        },
                        new
                        {
                            AccommodationId = 5,
                            Name = "Shibuya Luxury Hotel"
                        },
                        new
                        {
                            AccommodationId = 6,
                            Name = "Tokyo Bay Hotel"
                        });
                });

            modelBuilder.Entity("Anetia_TripApp.Models.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            ActivityId = 1,
                            Name = "Eiffel Tower Tour"
                        },
                        new
                        {
                            ActivityId = 2,
                            Name = "Louvre Museum Visit"
                        },
                        new
                        {
                            ActivityId = 3,
                            Name = "Seine River Cruise"
                        },
                        new
                        {
                            ActivityId = 4,
                            Name = "Notre-Dame Cathedral Tour"
                        },
                        new
                        {
                            ActivityId = 5,
                            Name = "Statue of Liberty Tour"
                        },
                        new
                        {
                            ActivityId = 6,
                            Name = "Times Square Visit"
                        },
                        new
                        {
                            ActivityId = 7,
                            Name = "Central Park Walk"
                        });
                });

            modelBuilder.Entity("Anetia_TripApp.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestinationId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            Name = "Paris"
                        },
                        new
                        {
                            DestinationId = 2,
                            Name = "New York"
                        },
                        new
                        {
                            DestinationId = 3,
                            Name = "Tokyo"
                        },
                        new
                        {
                            DestinationId = 4,
                            Name = "Dubai"
                        },
                        new
                        {
                            DestinationId = 5,
                            Name = "Singapore"
                        });
                });

            modelBuilder.Entity("Anetia_TripApp.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<int?>("AccommodationId")
                        .HasColumnType("int");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TripId");

                    b.HasIndex("AccommodationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("ActivityTrip", b =>
                {
                    b.HasOne("Anetia_TripApp.Models.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivitiesActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Anetia_TripApp.Models.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripsTripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Anetia_TripApp.Models.Trip", b =>
                {
                    b.HasOne("Anetia_TripApp.Models.Accommodation", "Accommodation")
                        .WithMany("Trips")
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Anetia_TripApp.Models.Destination", "Destination")
                        .WithMany("Trips")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Accommodation");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("Anetia_TripApp.Models.Accommodation", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Anetia_TripApp.Models.Destination", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
